CREATE TABLE IF NOT EXISTS kb_document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    doc_no VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    category VARCHAR(64) DEFAULT NULL,
    diagnose_type VARCHAR(32) DEFAULT NULL,
    app_id VARCHAR(64) DEFAULT NULL,
    env VARCHAR(32) DEFAULT NULL,
    source_ref VARCHAR(512) DEFAULT NULL,
    content_hash VARCHAR(64) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    quality_status VARCHAR(16) NOT NULL DEFAULT 'APPROVED',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    chunk_count INT NOT NULL DEFAULT 0,
    file_size BIGINT NOT NULL DEFAULT 0,
    error_message TEXT DEFAULT NULL,
    embedding_model VARCHAR(128) DEFAULT NULL,
    embedding_dimension INT DEFAULT NULL,
    uploaded_by VARCHAR(64) DEFAULT NULL,
    indexed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME DEFAULT NULL,
    UNIQUE KEY uk_kb_document_doc_no (doc_no),
    UNIQUE KEY uk_kb_document_content_hash (content_hash),
    KEY idx_kb_document_status (status),
    KEY idx_kb_document_source (source_type, category),
    KEY idx_kb_document_scope (diagnose_type, app_id, env)
);

CREATE TABLE IF NOT EXISTS kb_chunk (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    doc_id BIGINT NOT NULL,
    doc_no VARCHAR(64) NOT NULL,
    chunk_index INT NOT NULL,
    chunk_hash VARCHAR(64) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    vector_id VARCHAR(128) NOT NULL,
    token_count INT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_kb_chunk_position (doc_id, chunk_index),
    UNIQUE KEY uk_kb_chunk_vector_id (vector_id),
    KEY idx_kb_chunk_doc_no (doc_no),
    FULLTEXT KEY ft_kb_chunk_content (content) WITH PARSER ngram
);

CREATE TABLE IF NOT EXISTS diagnose_report_reference (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_no VARCHAR(64) NOT NULL,
    report_id BIGINT DEFAULT NULL,
    chunk_id BIGINT DEFAULT NULL,
    doc_no VARCHAR(64) NOT NULL,
    citation_code VARCHAR(16) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    title_snapshot VARCHAR(255) NOT NULL,
    source_ref_snapshot VARCHAR(512) DEFAULT NULL,
    similarity DECIMAL(7,6) DEFAULT NULL,
    retrieval_rank INT NOT NULL,
    usage_type VARCHAR(16) NOT NULL DEFAULT 'RETRIEVED',
    content_excerpt VARCHAR(1000) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_report_reference_citation (task_no, citation_code),
    KEY idx_report_reference_task (task_no, retrieval_rank),
    KEY idx_report_reference_report (report_id)
);
